baseurl = "/"
languageCode = "en-us"
title = "My NURD website"
theme = "hugo-lithium"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
enableEmoji = true

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1
[[menu.main]]
    name = "GitHub"
    pre = "fa-github-square"
    url = "https://github.com/csammutpowell"
    weight = 3
[[menu.main]]
    name = "Twitter"
    pre= "fa-twitter"
    url = "https://twitter.com/rstudio"
    weight = 2
[[menu.main]]
    name = "Posts"
    pre= "fa-bullhorn"
    url = "/post/"
    weight = 4

[params]
    description = "A website built through Hugo and blogdown. We can add any text we would like to appear on our home page. This is my first website design using blogdown at the workshop with Tanja at NU R Day."
    chapter="Manchester, UK"
    customCSS = ["css/datateka.css", "css/fontawesome.min.css"]

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    [params.logo]
    url = "DataTeka_logo.png"
    width = 50
    height = 50
    alt = "Logo"

